# Generated by Django 4.2.3 on 2023-08-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_banner_created_at_registration_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='kurs',
            field=models.CharField(choices=[('backend', 'backend'), ('frontend', 'frontend'), ('mobile', 'mobile'), ('robot', 'robot')], max_length=8),
        ),
    ]
